config/routes.rb
Mygoal::Application.routes.draw do
  resources :form_parqs, except: :index

  # User authentication
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  resources :user_sessions, only: [:new, :create, :destroy]

  # Users registration and panel
  resources :users
  resources :students, :controller => 'users'
  resources :teachers, :controller => 'users'

  # Teachers
  resources :trainings

  get "enrollments/search"
  get "enrollments/users"
  post "enrollments/enroll"
  resources :enrollments, only: [:index]


  # Project index
  get "home/welcome"
  root 'home#welcome'
end

app/models/training.rb
class Training < ActiveRecord::Base
  belongs_to :teacher

  has_many :exercises

  accepts_nested_attributes_for :exercises, reject_if: :all_blank, allow_destroy: true

  validates :name, :objective, :duration, :body_group, presence: true
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  skip_before_filter :require_login
  before_action :set_training, only: [:show, :edit, :update, :destroy]

  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = current_user.trainings
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
  end

  # GET /trainings/new
  def new
    @training = current_user.trainings.new
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = current_user.trainings.new(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'Treino criado com sucesso' }
        format.json { render action: 'show', status: :created, location: @training }
      else
        format.html { render action: 'new' }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to @training, notice: 'Alterações salvas com sucesso' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = current_user.trainings.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit(:name, :objective, :duration, :schedule, :body_group,
        exercises_attributes: [
          :id, :name, :repetitions, :series, :interval, :weight, :training_id, :_destroy
        ])
    end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_exercise_fields.html.erb
<tr class="nested-fields">
  <td><%= f.text_field :name, :class => "form-control" %></td>
  <td><%= f.text_field :repetitions, :class => "form-control", placeholder: 'Repetições' %></td>
  <td><%= f.text_field :series, :class => "form-control", placeholder: 'Séries' %></td>
  <td><%= f.text_field :interval, :class => "form-control", placeholder: 'Intervalo' %></td>
  <td><%= f.text_field :weight, :class => "form-control", placeholder: 'Peso' %></td>
  <td><%= link_to_remove_association "apagar exercício", f, class: 'btn btn-danger' %></td>
</tr>

app/views/trainings/_form.html.erb
<%= form_for(@training, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @training.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@training.errors.count, "error") %> prohibited this training from being saved:</h4>

      <ul>
      <% @training.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, 'Nome', :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :objective, 'Objetivo', :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :objective, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :duration, 'Duração', :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :duration, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :schedule, 'Rotina de Treino', :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :schedule, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :body_group, 'Tipo de Treino', :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :body_group, :class => "form-control" %>
    </div>
  </div>

  <div class="page_header">
    <h3>Exercícios</h3>
  </div>
  <div class="table-responsive">
    <table class="table-striped table-hover table">
      <thead>
        <tr>
          <th>Exercício</th>
          <th>Repetições</th>
          <th>Séries</th>
          <th>Intervalo</th>
          <th>Peso</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="exercises">
        <%= f.fields_for :exercises do |exercise| %>
          <%= render 'exercise_fields', :f => exercise %>
        <% end %>
      </tbody>
      <tfoot class="links">
        <tr>
          <td colspan="5"></td>
          <td><%= link_to_add_association 'adicionar exercício', f, :exercises, class: 'btn btn-info', :"data-association-insertion-node" => raw('table'), :"data-association-insertion-method" => "append" %></td>
        </tr>
      </tfoot>
    </table>
  </div>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit :class => "btn btn-primary btn-lg" %>
    </div>
  </div>
<% end %>

app/views/trainings/edit.html.erb
<div class="page-header">
  <%= link_to trainings_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar para Meus Treinos
  <% end %>
  <%= link_to @training, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Ver
  <% end %>
  <h1>Editando Treino <small><%= @training.try(:name) %></small></h1>
</div>

<%= render 'form' %>

app/views/trainings/index.html.erb
<div class="page-header">
  <%= link_to new_training_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Treino
  <% end %>
  <h1>Meus Treinos</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Duração</th>
        <th>Tipo de Treino</th>
        <th>Exercícios</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @trainings) do |training| %>
        <td><%= training.try(:name) %></td>
        <td><%= training.try(:duration) %></td>
        <td><%= training.try(:body_group) %></td>
        <td><%= training.exercises.map(&:name).join(', ') %></td>
        <td>
          <%= link_to 'Ver', training %> |
          <%= link_to 'Editar', edit_training_path(training) %> |
          <%= link_to 'Apagar', training, method: :delete, data: { confirm: 'Você tem certeza que deseja apagar este treino?' } %>
        </td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/trainings/new.html.erb
<div class="page-header">
  <%= link_to trainings_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar para Meus Treinos
  <% end %>
  <h1>Novo Treino</h1>
</div>

<%= render 'form' %>

app/views/trainings/show.html.erb
<div class="page-header">
  <%= link_to trainings_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar para Meus Treinos
  <% end %>
  <%= link_to edit_training_path(@training), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Treino <small><%= @training.try(:name) %></small></h1>
</div>

<dl class="dl-horizontal">
  <dt>Professor:</dt>
  <dd><%= @training.teacher.name %></dd>

  <dt>Objetivo:</dt>
  <dd><%= @training.try(:objective) %></dd>

  <dt>Duração:</dt>
  <dd><%= @training.try(:duration) %></dd>

  <dt>Rotina de Treino:</dt>
  <dd><%= @training.try(:schedule) %></dd>

  <dt>Tipo de Treino:</dt>
  <dd><%= @training.try(:body_group) %></dd>
</dl>

<div class="table-responsive">
  <table class="table-striped table-hover table">
    <thead>
      <tr>
        <th>Exercício</th>
        <th>Repetições</th>
        <th>Séries</th>
        <th>Intervalo</th>
        <th>Peso</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @training.exercises) do |exercise| %>
        <td><%= exercise.try(:name) %></td>
        <td><%= exercise.try(:repetitions) %></td>
        <td><%= exercise.try(:series) %></td>
        <td><%= exercise.try(:interval) %></td>
        <td><%= exercise.try(:weight) %></td>
      <% end %>
    </tbody>
  </table>
</div>