config/routes.rb
Mygoal::Application.routes.draw do
  resources :form_parqs, except: :index

  # User authentication
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  resources :user_sessions, only: [:new, :create, :destroy]

  # Users registration and panel
  resources :users
  resources :students, :controller => 'users'
  resources :teachers, :controller => 'users'

  # Teachers
  resources :trainings

  get "enrollments/search"
  get "enrollments/users"
  post "enrollments/enroll"
  resources :enrollments, only: [:index]


  # Project index
  get "home/welcome"
  root 'home#welcome'
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true

  validates :type, presence: true
end

app/models/users/student.rb
class Student < User
  has_and_belongs_to_many :teachers,
    foreign_key: 'student_id',
    association_foreign_key: 'teacher_id',
    join_table: 'teachers_students'

  has_one :form_parq,
    foreign_key: 'user_id'

  validates :name, :city, :state, presence: true

  # before_save :set_details

  # Default params for students
  # def set_details
  #   self.name = 'John Doe'
  # end
end

app/models/users/teacher.rb
class Teacher < User
  has_many :trainings

  has_and_belongs_to_many :students,
    foreign_key: 'teacher_id',
    association_foreign_key: 'student_id',
    join_table: 'teachers_students'

  validates :name, :city, :state, :short_bio, :document, :specialty, presence: true
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:new, :create]
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    redirect_to :users if current_user
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        login(@user.email, user_params[:password])
        format.html { redirect_to(:users, notice: 'Seja bem-vindo ao MYGOAL! Você se registrou com sucesso :)') }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Seu perfil foi atualizado com sucesso' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    logout
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      # Doing that to solve STI routes bug :(
      if params[:user].blank? && !params[:student].blank?
        sti_params = params.require(:student)
      elsif params[:user].blank? && !params[:teacher].blank?
        sti_params = params.require(:teacher)
      else
        sti_params = params.require(:user)
      end

      sti_params.permit(:email, :password, :password_confirmation,
        :name, :city, :state, :short_bio, :document, :specialty, :type)
    end
end

app/helpers/users_helper.rb
# encoding: UTF-8
# https://raw2.github.com/tapajos/brazilian-rails/master/brhelper/lib/brhelper/br_form_options_helper.rb
module UsersHelper
  ESTADOS_BRASILEIROS = [["Acre", "AC"],
    ["Alagoas", "AL"],
    ["Amapá", "AP"],
    ["Amazonas", "AM"],
    ["Bahia", "BA"],
    ["Ceará", "CE"],
    ["Distrito Federal", "DF"],
    ["Espírito Santo", "ES"],
    ["Goiás", "GO"],
    ["Maranhão", "MA"],
    ["Mato Grosso", "MT"],
    ["Mato Grosso do Sul", "MS"],
    ["Minas Gerais", "MG"],
    ["Pará", "PA"],
    ["Paraíba", "PB"],
    ["Paraná", "PR"],
    ["Pernambuco", "PE"],
    ["Piauí", "PI"],
    ["Rio de Janeiro", "RJ"],
    ["Rio Grande do Norte", "RN"],
    ["Rio Grande do Sul", "RS"],
    ["Rondônia", "RO"],
    ["Roraima", "RR"],
    ["Santa Catarina", "SC"],
    ["São Paulo", "SP"],
    ["Sergipe", "SE"],
    ["Tocantins", "TO"]
  ] unless const_defined?("ESTADOS_BRASILEIROS")

  # Helper para montar um select para seleção de estados brasileiros por nome,
  # mas com armazenamento da sigla.
  def select_estado(object, method, options = {}, html_options = {})
    select object, method, ESTADOS_BRASILEIROS, options, html_options
  end

  # Helper para montar um select para seleção de estados brasileiros por sigla.
  def select_uf(object, method, options = {}, html_options = {})
     select object, method, ESTADOS_BRASILEIROS.collect {|estado, sigla| sigla}, options, html_options
  end

  # Retorna uma string com a lista de estados brasileiros para usar em uma tag select,
  # com exibição do nome do estado, mas armazenando a sigla.
  def option_estados_for_select
    options_for_select ESTADOS_BRASILEIROS
  end

  # Retorna uma string com a lista de estados brasileiros para usar em uma tag select,
  # com exibição e armazenamento a sigla.
  def option_uf_for_select
    options_for_select ESTADOS_BRASILEIROS.collect {|nome,sigla| sigla}
  end

  # Helper para montar um select para seleção de sexo, armazenando apenas a
  # inicial.
  def select_sexo(object, method, options = {}, html_options = {})
    select object, method, [['Masculino', 'M'], ['Feminino', 'F']], options, html_options
  end
end

app/views/users/_form.html.erb
<%= form_for(@user, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@user.errors.count, "erro", "erros") %> não permitiram seu cadastro:</h4>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password, "Senha", :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.password_field :password, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, "Confirme a Senha", :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.password_field :password_confirmation, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :type, "Eu sou", :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.select :type, [["Aluno", "Student"], ["Professor", "Teacher"]] , :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :city, "Cidade/UF", :class => "col-lg-2 control-label" %>
    <div class="col-lg-8">
      <%= f.text_field :city, :class => "form-control" %>
    </div>
    <div class="col-lg-2">
      <%= f.select :state, option_estados_for_select %>
    </div>
  </div>

  <div class="form-group teacher_field">
    <%= f.label :specialty, "Especialidade", :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :specialty, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group teacher_field">
    <%= f.label :document, "CREF", :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :document, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group teacher_field">
    <%= f.label :short_bio, "Pequeno Currículo", :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :short_bio, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/_student_dashboard.html.erb
<div class="page-header">
  <h1>Olá <%= current_user.name %>! <small>Esse é sua dashboard</small></h1>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="well">
    <% if current_user.teachers.empty? %>
      Você não possui nenhum professor associado a sua conta. <%= link_to 'Procurar professores', enrollments_path %>
    <% else %>
      <ul>
      <% current_user.teachers.each do |teacher| %>
        <li><%= link_to teacher.name, teacher %></li>
      <% end %>
      </ul>
    <% end %>
    </div>
  </div>

  <div class="col-lg-12">
    <div class="well">
      Você não possui treinos para execução. <%= link_to 'Procurar treinos', '#' %>
    </div>
  </div>

  <div class="col-lg-12">
    <%= link_to "Enviar relatório de execução de treino", '#', class: 'btn btn-default btn-lg btn-info btn-block' %>
  </div>

  <div class="col-lg-12">
    <br>
    <%= link_to "Enviar formulário de PAR-Q", new_form_parq_path, class: 'btn btn-default btn-lg btn-info btn-block' %>
  </div>


</div>

app/views/users/_teacher_dashboard.html.erb
<div class="page-header">
  <h1>Olá <%= current_user.name %>! <small>Esse é sua dashboard</small></h1>
</div>

<div class="row">
  <% if current_user.trainings.empty? %>
  <div class="col-lg-6">
    <div class="well">
      Você ainda não criou um treino. <br>
      <%= link_to "Crie seu primeiro treino", new_training_path, class: 'btn btn-primary' %>
    </div>
  </div>
  <% else %>
  <div class="col-lg-6">
    <%= link_to "Meus Treinos", trainings_path, class: 'btn btn-default btn-lg btn-info btn-block' %>
  </div>
  <% end %>




  <% if 1 == 1 %>
  <div class="col-lg-6">
    <div class="well">
      <% if current_user.students.empty? %>
        Você não possui alunos associados. <br>
        <%= link_to "Buscar alunos", '#', class: 'btn btn-primary' %>
      <% else %>
        <p>Meus alunos</p>
        <ul>
        <% current_user.students.each do |student| %>
          <li><%= link_to student.name, student %></li>
        <% end %>
        </ul>
      <% end %>
    </div>
  </div>
  <% else %>
  <div class="col-lg-6 well">
    <p>Últimos relatórios enviados:</p>

    <ul>
      <li><a href="#">João dos Santos</a></li>
      <li><a href="#">Maria José de Conceição</a></li>
      <li><a href="#">Juliana Lebllof</a></li>
    </ul>
    <%= link_to "Meus Alunos", '#', class: 'btn btn-default btn-lg btn-info btn-block' %>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="page-header">
  <%= link_to users_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Dashboard
  <% end %>
  <h1>Meus dados</h1>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<%= render partial: "users/#{current_user.type.downcase}_dashboard" %>

<br><br><br><br><br><br>
<div class="page-header">
  <h4>Apagar minha conta</h4>
</div>
<%= link_to 'Quero apagar minha conta', current_user, method: :delete, class: 'btn btn-danger', data: { confirm: 'Você tem certeza disso? Todos seus dados serão removidos portanto essa ação não terá retorno.' } %>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Cadastre-se</h1>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="page-header">
  <%= link_to users_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_user_path(@user), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show user</h1>
</div>

<dl class="dl-horizontal">
  <dt>Email:</dt>
  <dd><%= @user.email %></dd>

</dl>