config/routes.rb
Mygoal::Application.routes.draw do
  resources :form_parqs, except: :index

  # User authentication
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  resources :user_sessions, only: [:new, :create, :destroy]

  # Users registration and panel
  resources :users
  resources :students, :controller => 'users'
  resources :teachers, :controller => 'users'

  # Teachers
  resources :trainings

  get "enrollments/search"
  get "enrollments/users"
  post "enrollments/enroll"
  resources :enrollments, only: [:index]


  # Project index
  get "home/welcome"
  root 'home#welcome'
end

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= msg %>
  <% end %>
<% end %>

app/views/shared/_navigation.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MYGOAL", root_path, :class => "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
      <% if current_user %>
        <li><%= link_to "Dashboard", users_path %></li>
        <% if current_user.is_a? Teacher %>
          <li><%= link_to "Meus Treinos", trainings_path %></li>
          <li><%= link_to "Alunos", enrollments_path %></li>
        <% elsif current_user.is_a? Student %>
          <li><%= link_to "Meus Treinos", '#' %></li>
          <li><%= link_to "Professores", enrollments_path %></li>
        <% end %>
      <% else %>
        <li><%= link_to "Home", root_path %></li>
        <li><a href="#">Sobre</a></li>
        <li><a href="#">Contato</a></li>
      <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="useractions"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu" aria-labelledby="useractions">
              <li><%= link_to "Editar Perfil", edit_user_path(current_user.id) %></li>
              <li><%= link_to "Sair", :logout, method: :post %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Cadastre-se", new_user_path %></li>
          <li><%= link_to "Entrar", :login %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>