config/routes.rb
Mygoal::Application.routes.draw do
  resources :form_parqs, except: :index

  # User authentication
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  resources :user_sessions, only: [:new, :create, :destroy]

  # Users registration and panel
  resources :users
  resources :students, :controller => 'users'
  resources :teachers, :controller => 'users'

  # Teachers
  resources :trainings

  get "enrollments/search"
  get "enrollments/users"
  post "enrollments/enroll"
  resources :enrollments, only: [:index]


  # Project index
  get "home/welcome"
  root 'home#welcome'
end

app/models/form_parq.rb
class FormParq < ActiveRecord::Base
  belongs_to :student,
    foreign_key: 'user_id'
end

app/controllers/form_parqs_controller.rb
class FormParqsController < ApplicationController
  before_action :set_form_parq, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login

  # def index
  #   @form_parqs = FormParq.all
  # end

  # GET /form_parqs/1
  # GET /form_parqs/1.json
  def show
  end

  # GET /form_parqs/new
  def new
    if current_user.form_parq.nil?
      @form_parq = current_user.build_form_parq
    else
      redirect_to current_user.form_parq
    end
  end

  # GET /form_parqs/1/edit
  def edit
    @form_parq = current_user.form_parq.nil? ? current_user.build_form_parq : current_user.form_parq
  end

  # POST /form_parqs
  # POST /form_parqs.json
  def create
    @form_parq = current_user.build_form_parq(form_parq_params)

    respond_to do |format|
      if @form_parq.save
        format.html { redirect_to @form_parq, notice: 'Formulário de PAR-Q preenchido com sucesso.' }
        format.json { render action: 'show', status: :created, location: @form_parq }
      else
        format.html { render action: 'new' }
        format.json { render json: @form_parq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /form_parqs/1
  # PATCH/PUT /form_parqs/1.json
  def update
    respond_to do |format|
      if @form_parq.update(form_parq_params)
        format.html { redirect_to @form_parq, notice: 'Form parq was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @form_parq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /form_parqs/1
  # DELETE /form_parqs/1.json
  def destroy
    @form_parq.destroy
    respond_to do |format|
      format.html { redirect_to form_parqs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form_parq
      @form_parq = FormParq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_parq_params
      params.require(:form_parq).permit(:answer1, :answer2, :answer3, :answer4, :answer5, :answer6, :answer7, :user_id)
    end
end

app/helpers/form_parqs_helper.rb
module FormParqsHelper
end

app/views/form_parqs/_form.html.erb
<%= form_for(@form_parq, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @form_parq.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@form_parq.errors.count, "error") %> prohibited this form_parq from being saved:</h4>

      <ul>
      <% @form_parq.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :answer1, "Alguma vez um médico lhe disse que você possui um problema do coração e lhe recomendou que só fizesse atividade física sob supervisão médica?", :class => "col-lg-11 control-label" %>
    <div class="col-lg-1">
      <%= f.check_box :answer1, :class => "form-control" %> Sim
    </div>
  </div>
  <div class="form-group">
    <%= f.label :answer2, "Você sente dor no peito, causada pela prática de atividade física?", :class => "col-lg-11 control-label" %>
    <div class="col-lg-1">
      <%= f.check_box :answer2, :class => "form-control" %> Sim
    </div>
  </div>
  <div class="form-group">
    <%= f.label :answer3, "Você sentiu dor no peito no último mês?", :class => "col-lg-11 control-label" %>
    <div class="col-lg-1">
      <%= f.check_box :answer3, :class => "form-control" %> Sim
    </div>
  </div>
  <div class="form-group">
    <%= f.label :answer4, "Você tende a perder a consciência ou cair, como resultado de tonteira ou desmaio?", :class => "col-lg-11 control-label" %>
    <div class="col-lg-1">
      <%= f.check_box :answer4, :class => "form-control" %> Sim
    </div>
  </div>
  <div class="form-group">
    <%= f.label :answer5, "Você tem algum problema ósseo ou muscular que poderia ser agravado com a prática de atividade física?", :class => "col-lg-11 control-label" %>
    <div class="col-lg-1">
      <%= f.check_box :answer5, :class => "form-control" %> Sim
    </div>
  </div>
  <div class="form-group">
    <%= f.label :answer6, "Algum médico já lhe recomendou o uso de medicamentos para a sua pressão arterial, para circulação ou coração?", :class => "col-lg-11 control-label" %>
    <div class="col-lg-1">
      <%= f.check_box :answer6, :class => "form-control" %> Sim
    </div>
  </div>
  <div class="form-group">
    <%= f.label :answer7, "Você tem consciência, através da sua própria experiência ou aconselhamento médico, de alguma outra razão física que impeça sua prática de atividade física sem supervisão médica?", :class => "col-lg-11 control-label" %>
    <div class="col-lg-1">
      <%= f.check_box :answer7, :class => "form-control" %> Sim
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-6 col-lg-6">
      <%= f.submit "Enviar", :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/form_parqs/edit.html.erb
<div class="page-header">
  <%= link_to users_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>PAR-Q <small>Questionário de Prontidão para Atividade Física</small></h1>
</div>

<p>Autoridades Canadenses desenvolveram esse questionário que deve ser aplicado antes do início de um programa de atividade física regular, visando identificar prováveis restrições e limitações à saúde.</p>

<%= render 'form' %>

<p>Se apenas uma das questões for respondida com um sim, seria recomendado uma avaliação de um medico antes do início do programa.</p>
<p>Este instrumento é apenas uma ferramenta na tentativa da identificação dos riscos com a prática da atividade física e não é infalível. Instituições como o Colégio Americano de Medicina Desportiva e a Sociedade Brasileira de Cardiologia, recomendam a realização de exames complementares como o teste de esforço, e o exame sangüíneo. Procedimentos recomendados principalmente para indivíduos sintomáticos, indivíduos com doenças conhecidas como a hipertensão arterial, a diabetes, a obesidade, as doenças cardiovasculares ou para indivíduos acima dos trinta e cinco anos.</p>

app/views/form_parqs/index.html.erb
<div class="page-header">
  <%= link_to new_form_parq_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Form parq
  <% end %>

</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>User</th>
            <th>Answer1</th>
            <th>Answer</th>
            <th>Answer3</th>
            <th>Answer4</th>
            <th>Answer5</th>
            <th>Answer6</th>
            <th>Answer7</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @form_parqs) do |form_parq| %>
            <td><%= form_parq.user_id %></td>
            <td><%= form_parq.answer1 %></td>
            <td><%= form_parq.answer %></td>
            <td><%= form_parq.answer3 %></td>
            <td><%= form_parq.answer4 %></td>
            <td><%= form_parq.answer5 %></td>
            <td><%= form_parq.answer6 %></td>
            <td><%= form_parq.answer7 %></td>
            <td><%= link_to 'Show', form_parq %></td>
        <td><%= link_to 'Edit', edit_form_parq_path(form_parq) %></td>
        <td><%= link_to 'Destroy', form_parq, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/form_parqs/new.html.erb
<div class="page-header">
  <%= link_to users_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>PAR-Q <small>Questionário de Prontidão para Atividade Física</small></h1>
</div>

<p>Autoridades Canadenses desenvolveram esse questionário que deve ser aplicado antes do início de um programa de atividade física regular, visando identificar prováveis restrições e limitações à saúde.</p>

<%= render 'form' %>

<p>Se apenas uma das questões for respondida com um sim, seria recomendado uma avaliação de um medico antes do início do programa.</p>
<p>Este instrumento é apenas uma ferramenta na tentativa da identificação dos riscos com a prática da atividade física e não é infalível. Instituições como o Colégio Americano de Medicina Desportiva e a Sociedade Brasileira de Cardiologia, recomendam a realização de exames complementares como o teste de esforço, e o exame sangüíneo. Procedimentos recomendados principalmente para indivíduos sintomáticos, indivíduos com doenças conhecidas como a hipertensão arterial, a diabetes, a obesidade, as doenças cardiovasculares ou para indivíduos acima dos trinta e cinco anos.</p>

app/views/form_parqs/show.html.erb
<div class="page-header">
  <%= link_to users_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>PAR-Q <small>Questionário de Prontidão para Atividade Física</small></h1>
</div>

<dt>Aluno:</dt>
<dd><%= @form_parq.student.try(:name) %></dd>

<div class="table-responsive">
  <table class="table-striped table-hover table">
    <thead>
      <tr>
        <th>Pergunta</th>
        <th>Resposta</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Alguma vez um médico lhe disse que você possui um problema do coração e lhe recomendou que só fizesse atividade física sob supervisão médica?</td>
        <td><%= @form_parq.answer1 %></td>
      </tr>
      <tr>
        <td>Você sente dor no peito, causada pela prática de atividade física?</td>
        <td><%= @form_parq.answer2 %></td>
      </tr>
      <tr>
        <td>Você sentiu dor no peito no último mês?</td>
        <td><%= @form_parq.answer3 %></td>
      </tr>
      <tr>
        <td>Você tende a perder a consciência ou cair, como resultado de tonteira ou desmaio?</td>
        <td><%= @form_parq.answer4 %></td>
      </tr>
      <tr>
        <td>Você tem algum problema ósseo ou muscular que poderia ser agravado com a prática de atividade física?</td>
        <td><%= @form_parq.answer5 %></td>
      </tr>
      <tr>
        <td>Algum médico já lhe recomendou o uso de medicamentos para a sua pressão arterial, para circulação ou coração?</td>
        <td><%= @form_parq.answer6 %></td>
      </tr>
      <tr>
        <td>Você tem consciência, através da sua própria experiência ou aconselhamento médico, de alguma outra razão física que impeça sua prática de atividade física sem supervisão médica?</td>
        <td><%= @form_parq.answer7 %></td>
      </tr>
    </tbody>
  </table>
</div>